### ISSUE TITLE
django import error

### ISSUE THREAD

**Issue by sevinty7** [crits/crits#1024]
When running the bootstrap script I get an error when trying to create an admin user for the mongo db. 

I've pasted the error below. 

`Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`

**Comment by apolkosnik** [comment]
Can you run "pip freeze | grep ngo"?

**Comment by sevinty7** [comment]
Comes back with nothing.

**Comment by apolkosnik** [comment]
It looks like you might want to CD to /data/crits and  install the requirements with "sudo -E pip install -r requirements.txt"

**Comment by sevinty7** [comment]
I manually installed the requirements with the requirements.txt now. I run the boostrap script and get this error while trying to start mongodb. 

`Do you want to start 'mongod' now? [yn] y
Starting Server
To Restart Server: script/bootstrap 4
Warning MongoDB Will Still be Running After Server Ends
about to fork child process, waiting until server is ready for connections.
forked process: 8659
ERROR: child process failed, exited with error number 1
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/__init__.py", line 1, in <module>
    from crits.settings import CRITS_VERSION as __version__
  File "/data/crits/crits/settings.py", line 218, in <module>
    crits_config = coll.find_one({})
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/collection.py", line 1262, in find_one
    for result in cursor.limit(-1):
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/cursor.py", line 1087, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused`

**Comment by apolkosnik** [comment]
Ugh, when the bootstrap was done virtualenv wasn't considered, so you might want to just rewrite the bootstraps to do it the way that it takes virtualenv into the account.

**Comment by apolkosnik** [comment]
The error now shows that your mongodb is not running

**Comment by sevinty7** [comment]
I was able to get it up and running. I had to do a combination of running the bootstrap script as well as installing many things manually. I had to manually add the repo and install mongodb-org in order to clear up the mongodb errors. I had to install at least 4 different python dependencies for when the bootstrap script was setting up mongo. It's up now and I'll try to replicate the process in the near future to get a more concise list of steps I took. Thanks for the help.
