### ISSUE TITLE
stable_4 requirements.txt does not pull correct versions for install

### ISSUE THREAD

**Issue by christauff** [crits/crits#1025]
We cannot get Stable_4 to build with a clean empty DB, then successfully start up. 

We are aware, from speaking with the lead devs, that there may be version issues with dependencies. So, we spent some time trying to get rid of the incompatible packages. 

When using the ORIGINAL requirements.txt in the Stable_4 branch, the following output is observed:

**_TL;DR:_**
django-celery 3.2.2 has requirement celery<4.0,>=3.1.15, but you'll have celery 4.2.1 which is **incompatible**.
django-debug-toolbar 1.10.1 has requirement Django>=1.11, but you'll have django 1.8.19 which is **incompatible**.
django-mongoengine 0.3 has requirement django>=1.11, but you'll have django 1.8.19 which is **incompatible**.
django-mongoengine 0.3 has requirement mongoengine>=0.14, but you'll have mongoengine 0.10.6 which is **incompatible**.

```
crits@crits:/data/crits$ sudo -H pip install -U -r requirements.txt

Collecting git+https://github.com/brianz/django-debug-toolbar-mongo.git (from -r requirements.txt (line 11))
  Cloning https://github.com/brianz/django-debug-toolbar-mongo.git to /tmp/pip-req-build-8wq81S
Collecting git+https://github.com/frbapolkosnik/django-tastypie-mongoengine.git (from -r requirements.txt (line 16))
  Cloning https://github.com/frbapolkosnik/django-tastypie-mongoengine.git to /tmp/pip-req-build-t9Z2wT
Collecting git+https://github.com/MongoEngine/django-mongoengine.git (from -r requirements.txt (line 21))
  Cloning https://github.com/MongoEngine/django-mongoengine.git to /tmp/pip-req-build-PUbBYf
Collecting Django<1.9 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/96/b9/b4108da1275dc2ac1bba1e87739cb31b3d44339affb83b0e949fb09c2bef/Django-1.8.19-py2.py3-none-any.whl
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (5.3.0)
Collecting amqp (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/cf/12d4611fc67babd4ae250c9e8249c5650ae1933395488e9e7e3562b4ff24/amqp-2.3.2-py2.py3-none-any.whl
Requirement already up-to-date: anyjson in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.3.3)
Collecting billiard (from -r requirements.txt (line 5))
Requirement already up-to-date: biplist in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (1.0.3)
Collecting celery (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/e8/58/2a0b1067ab2c12131b5c089dfc579467c76402475c5231095e36a43b749c/celery-4.2.1-py2.py3-none-any.whl
Requirement already up-to-date: defusedxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (0.5.0)
Requirement already up-to-date: django-celery in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9)) (3.2.2)
Collecting django-debug-toolbar (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/97/c6/523fc2ca98119d21c709bbc47217b1d5fd17c6f9449ef32490889363d97d/django_debug_toolbar-1.10.1-py2.py3-none-any.whl
Requirement already up-to-date: django-debug-toolbar-template-profiler in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (1.0.2)
Requirement already up-to-date: django-debug-toolbar-template-timings in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (0.9)
Requirement already up-to-date: django-debug-toolbar-vcs-info in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (1.2.0)
Requirement already up-to-date: django-tastypie==0.13.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15)) (0.13.3)
Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17)) (0.16.0)
Collecting kombu (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/97/61/65838c7da048e56d549e358ac19c0979c892e17dc6186610c49531d35b70/kombu-4.2.1-py2.py3-none-any.whl
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19)) (4.2.5)
Collecting mongoengine==0.10.6 (from -r requirements.txt (line 20))
Requirement already up-to-date: pip>=8.1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22)) (18.1)
Requirement already up-to-date: pydeep==0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23)) (0.2)
Requirement already up-to-date: pymongo==3.2.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 24)) (3.2.2)
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 25)) (2.2.2)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 26)) (2.7.3)
Requirement already up-to-date: python-ldap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 27)) (3.1.0)
Requirement already up-to-date: python-magic==0.4.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 28)) (0.4.6)
Requirement already up-to-date: python-mimeparse in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 29)) (1.6.0)
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 30)) (2018.5)
Requirement already up-to-date: pyyaml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 31)) (3.13)
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 32)) (2.20.0)
Requirement already up-to-date: setuptools>=28.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 33)) (40.4.3)
Requirement already up-to-date: simplejson in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 34)) (3.16.0)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 35)) (1.11.0)
Requirement already up-to-date: ushlex in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 36)) (0.99.1)
Requirement already up-to-date: wsgiref in /usr/lib/python2.7 (from -r requirements.txt (line 37)) (0.1.2)
Requirement already up-to-date: olefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 38)) (0.46)
Requirement already up-to-date: pyimpfuzzy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 39)) (0.5)
Requirement already up-to-date: m2crypto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 40)) (0.30.1)
Requirement already satisfied, skipping upgrade: vine>=1.1.3 in /usr/local/lib/python2.7/dist-packages (from amqp->-r requirements.txt (line 3)) (1.1.4)
Requirement already satisfied, skipping upgrade: sqlparse>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar->-r requirements.txt (line 10)) (0.2.4)
Requirement already satisfied, skipping upgrade: dateutils in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar-vcs-info->-r requirements.txt (line 14)) (0.6.6)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.1.5 in /usr/local/lib/python2.7/dist-packages (from python-ldap->-r requirements.txt (line 27)) (0.2.2)
Requirement already satisfied, skipping upgrade: pyasn1>=0.3.7 in /usr/local/lib/python2.7/dist-packages (from python-ldap->-r requirements.txt (line 27)) (0.4.4)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 32)) (1.22)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 32)) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 32)) (2.6)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 32)) (2017.7.27.1)
Requirement already satisfied, skipping upgrade: pefile in /usr/local/lib/python2.7/dist-packages (from pyimpfuzzy->-r requirements.txt (line 39)) (2017.9.3)
Requirement already satisfied, skipping upgrade: typing in /usr/local/lib/python2.7/dist-packages (from m2crypto->-r requirements.txt (line 40)) (3.6.2)
Requirement already satisfied, skipping upgrade: argparse in /usr/lib/python2.7 (from dateutils->django-debug-toolbar-vcs-info->-r requirements.txt (line 14)) (1.2.1)
Building wheels for collected packages: django-debug-toolbar-mongo, django-tastypie-mongoengine, django-mongoengine
  Running setup.py bdist_wheel for django-debug-toolbar-mongo ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-8jbkEa/wheels/41/27/eb/15d21c19f07eaabd16d956ee90db750723995b049c31b61d64
  Running setup.py bdist_wheel for django-tastypie-mongoengine ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-8jbkEa/wheels/e6/11/85/ba3fa354ee2fa1eec255c28de7b7b43d2aacf7e1eebb8312cf
  Running setup.py bdist_wheel for django-mongoengine ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-8jbkEa/wheels/d5/37/1e/452a29f007e7f47134c8b12fa3a7eeefc96162f9f00634afa1
Successfully built django-debug-toolbar-mongo django-tastypie-mongoengine django-mongoengine
django-celery 3.2.2 has requirement celery<4.0,>=3.1.15, but you'll have celery 4.2.1 which is incompatible.
django-debug-toolbar 1.10.1 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
django-mongoengine 0.3 has requirement django>=1.11, but you'll have django 1.8.19 which is incompatible.
django-mongoengine 0.3 has requirement mongoengine>=0.14, but you'll have mongoengine 0.10.6 which is incompatible.
Installing collected packages: Django, amqp, billiard, kombu, celery, django-debug-toolbar, mongoengine, django-debug-toolbar-mongo, django-tastypie-mongoengine, django-mongoengine
  Found existing installation: Django 1.8.13
    Uninstalling Django-1.8.13:
      Successfully uninstalled Django-1.8.13
  Found existing installation: amqp 1.4.9
    Uninstalling amqp-1.4.9:
      Successfully uninstalled amqp-1.4.9
  Found existing installation: billiard 3.3.0.23
    Uninstalling billiard-3.3.0.23:
      Successfully uninstalled billiard-3.3.0.23
  Found existing installation: kombu 3.0.37
    Uninstalling kombu-3.0.37:
      Successfully uninstalled kombu-3.0.37
  Found existing installation: celery 3.1.26.post2
    Uninstalling celery-3.1.26.post2:
      Successfully uninstalled celery-3.1.26.post2
  Found existing installation: django-debug-toolbar 1.8
    Uninstalling django-debug-toolbar-1.8:
      Successfully uninstalled django-debug-toolbar-1.8
  Found existing installation: mongoengine 0.15.3
    Uninstalling mongoengine-0.15.3:
      Successfully uninstalled mongoengine-0.15.3
  Found existing installation: django-debug-toolbar-mongo -versiontools-debug-toolbar-mongo-
    Uninstalling django-debug-toolbar-mongo--versiontools-debug-toolbar-mongo-:
      Successfully uninstalled django-debug-toolbar-mongo--versiontools-debug-toolbar-mongo-
  Found existing installation: django-tastypie-mongoengine 0.4.7
    Uninstalling django-tastypie-mongoengine-0.4.7:
      Successfully uninstalled django-tastypie-mongoengine-0.4.7
  Found existing installation: django-mongoengine 0.2.1
    Uninstalling django-mongoengine-0.2.1:
      Successfully uninstalled django-mongoengine-0.2.1
Successfully installed Django-1.8.19 amqp-2.3.2 billiard-3.5.0.4 celery-4.2.1 django-debug-toolbar-1.10.1 django-debug-toolbar-mongo--versiontools-debug-toolbar-mongo- django-mongoengine-0.3 django-tastypie-mongoengine-0.4.7 kombu-4.2.1 mongoengine-0.10.6
crits@crits:/data/crits$
```
We then edited the requirements.txt file to get rid of the various incompatible package issues. (see below for contents)

After trying to run to script bootstrap start server (sh script/server), all looks like it successfully installed, but I get the following traceback error:

```
crits@crits:/data/crits$ sh script/server
script/server: 12: [: 0: unexpected operator
Attempting to start runserver on port 8080
2162
Unhandled exception in thread started by <function wrapper at 0x2b2e011336e0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/services/__init__.py", line 1, in <module>
    from core import ServiceManager as svc_manager
  File "/data/crits/crits/services/core.py", line 18, in <module>
    from crits.services.analysis_result import EmbeddedAnalysisResultLog, AnalysisConfig
  File "/data/crits/crits/services/analysis_result.py", line 31, in <module>
    Document):
  File "/data/crits/crits/services/analysis_result.py", line 91, in AnalysisResult
    results = ListField(DynamicField(DictField))
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 89, in __init__
    raise TypeError('db_field should be a string.')
TypeError: db_field should be a string.
```

Source: [pip_freeze.txt](https://github.com/crits/crits/files/2507054/pip_freeze.txt)
Our **edited** [requirements.txt](https://github.com/crits/crits/files/2507055/requirements.txt)

Our pip freeze output:
```
amqp==1.4.9
anyjson==0.3.3
argcomplete==0.8.1
argh==0.26.1
arrow==0.10.0
asn1crypto==0.24.0
bcrypt==2.0.0
billiard==3.3.0.23
biplist==1.0.3
bitstring==3.1.5
blessings==1.6
bpython==0.15
bundle==1.1.2
celery==3.1.26.post2
certifi==2017.7.27.1
cffi==1.11.5
chardet==3.0.4
cryptography==2.3.1
curtsies==0.2.6
DateTime==4.3
dateutils==0.6.6
decorator==4.0.6
defusedxml==0.5.0
Django==1.8.13
django-celery==3.2.2
django-debug-toolbar==1.8
django-debug-toolbar-mongo===-versiontools-debug-toolbar-mongo-
django-debug-toolbar-template-profiler==1.0.2
django-debug-toolbar-template-timings==0.9
django-debug-toolbar-vcs-info==1.2.0
django-mongoengine==0.2.1
django-tastypie==0.13.3
django-tastypie-mongoengine==0.4.7
Dumper==1.0.4
enum34==1.1.2
FlexTransform==1.2.1
flup==1.0.2
formatter==1.0.3
future==0.16.0
greenlet==0.4.9
idna==2.6
ipaddress==1.0.16
ipython==2.4.1
isodate==0.6.0
kombu==3.0.37
logging==0.4.9.6
lqmt==1.4.0
lxml==4.2.5
M2Crypto==0.30.1
mixbox==1.0.2
mmbot==1.0.9
mod-pywebsocket==0.7.9
mongoengine==0.15.3
ndg-httpsclient==0.4.0
netaddr==0.7.19
numpy==1.13.3
olefile==0.46
oletools==0.50
ordered-set==2.0.2
ordereddict==1.1
pan-python==0.12.0
pandas==0.20.1
pathtools==0.1.2
pefile==2017.9.3
pep8==1.7.1
pexpect==4.0.1
Pillow==5.3.0
psycopg2==2.6.1
ptyprocess==0.5
pyasn1==0.4.4
pyasn1-modules==0.2.2
pychm==0.8.4.1
pycparser==2.19
pycrypto==2.6.1
pydeep==0.2
Pygments==2.1
pyimpfuzzy==0.5
pylzma==0.4.9
pymongo==3.2.2
PyMySQL==0.7.2
pynids==0.6.2
pyOpenSSL==18.0.0
pyparsing==2.2.2
pype32==0.1a5
pysqlite==1.0.1
python-dateutil==2.7.3
python-ldap==3.1.0
python-magic==0.4.6
python-memcached==1.53
python-mimeparse==1.6.0
pythonwhois==2.4.3
pytz==2018.5
PyYAML==3.13
qrcode==6.0
rdflib==4.2.2
requests==2.20.0
scikit-learn==0.18.2
scipy==0.19.0
simplegeneric==0.8.1
simplejson==3.16.0
six==1.11.0
sqlparse==0.2.4
stix-validator==2.5.0
toml==0.9.3
typing==3.6.2
urllib3==1.22
urwid==1.3.1
ushlex==0.99.1
vine==1.1.4
watchdog==0.8.3
wcwidth==0.1.6
weakrefmethod==1.0.3
whois==0.7
xlrd==1.1.0
yara==1.7.7
yolk==0.4.3
zope.interface==4.4.3
```

Our current **edited** requirements.txt:
```
Django==1.8.13
Pillow
amqp<2.0,>=1.4.5
anyjson
billiard<3.4,>=3.3.0.18
biplist
celery<4.0,>=3.1.15
defusedxml
django-celery
# django-debug-toolbar
django-debug-toolbar==1.8
git+https://github.com/brianz/django-debug-toolbar-mongo.git
django-debug-toolbar-template-profiler
django-debug-toolbar-template-timings
django-debug-toolbar-vcs-info
django-tastypie==0.13.3
git+https://github.com/frbapolkosnik/django-tastypie-mongoengine.git
future
kombu<3.1,>=3.0.23
lxml
mongoengine>=0.14
git+https://github.com/MongoEngine/django-mongoengine.git@v0.2.1
pip>=8.1.2
pydeep==0.2
pymongo==3.2.2
pyparsing
python-dateutil
python-ldap
python-magic==0.4.6
python-mimeparse
pytz
pyyaml
requests
setuptools>=28.3.0
simplejson
six
ushlex
wsgiref
olefile
pyimpfuzzy
m2crypto
```

**Comment by carterchurch** [comment]
I believe that the stable-4 dependency issue was resolved alongside the performance improvements in #1036 and the mongo issue that you were experiencing was resolved in #1037

**Comment by apolkosnik** [comment]
I think that after #1038, this should be resolved. Please try and let me know.

**Comment by christauff** [comment]
I'll check it out, thank you!
