### ISSUE TITLE
mongoengine.connection.ConnectionFailure: A different connection with alias `default` was already registered. Use disconnect() first

### ISSUE THREAD

**Issue by johncrits** [crits/crits#1070]
h!
i try many times to install the crits but i stock on same error i followed two guide first [one](https://github.com/crits/crits/wiki/Production-grade-CRITs-install) and second [one](https://www.secopshub.com/t/installing-crits-collaborative-research-into-threats-on-ubuntu-16-04-lts-x64-part-1/136)
the operating system is Ubuntu 20.04 LTS python packages are below 

amqp                                   1.4.9
anyjson                                0.3.3
billiard                               3.3.0.23
biplist                                1.0.3
celery                                 3.1.24
certifi                                2021.5.30
chardet                                4.0.0
configparser                           4.0.2
contextlib2                            0.6.0.post1
dateutils                              0.6.12
defusedxml                             0.7.1
Django                                 1.11.29
django-celery                          3.3.1
django-debug-toolbar                   1.11.1
django-debug-toolbar-mongo             0.3.1
django-debug-toolbar-template-profiler 2.0.2
django-debug-toolbar-template-timings  0.9
django-debug-toolbar-vcs-info          1.2.0
django-mongoengine                     0.3
django-tastypie                        0.14.3
django-tastypie-mongoengine            0.4.6+work4.3
future                                 0.18.2
idna                                   2.10
importlib-metadata                     2.1.1
kombu                                  3.0.37
lxml                                   4.6.3
mongoengine                            0.19.1
olefile                                0.46
pathlib2                               2.3.5
pefile                                 2019.4.18
Pillow                                 6.2.2
pip                                    20.3.4
pyasn1                                 0.4.8
pyasn1-modules                         0.2.8
pycrypto                               2.6.1
pydeep                                 0.4
pyimpfuzzy                             0.5
pymongo                                3.11.4
pyparsing                              2.4.7
python-dateutil                        2.8.1
python-ldap                            3.3.1
python-magic                           0.4.24
python-mimeparse                       1.6.0
pytz                                   2021.1
PyYAML                                 5.4.1
qrcode                                 6.1
requests                               2.25.1
scandir                                1.10.0
setuptools                             44.1.1
simplejson                             3.17.2
six                                    1.16.0
sqlparse                               0.3.1
urllib3                                1.26.5
ushlex                                 0.99.1
vine                                   1.3.0
wheel                                  0.36.2
wrapt                                  1.12.1
zipp                                   1.2.0

john@rambo:/data$ sudo python /data/crits/manage.py users  -a -u admin -e admin@localhost.com -R UberAdmin
Traceback (most recent call last):
  File "/data/crits/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/core/management/commands/users.py", line 9, in <module>
    import settings
  File "/data/crits/crits/settings.py", line 200, in <module>
    replicaset=MONGO_REPLICASET)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/connection.py", line 402, in connect
    raise ConnectionFailure(err_msg)
mongoengine.connection.ConnectionFailure: A different connection with alias `default` was already registered. Use disconnect() first

**Comment by m-katunar** [comment]
Hello!

Any potential updates on this issue?

Just ran into it, so any useful feedback would be greatly appreciated.

Thanks!

**Comment by dionisimus** [comment]
Try to install older version of django-tastypie e.g.:
`pip install django-tastypie==0.14.2`

**Comment by m-katunar** [comment]
> Try to install older version of django-tastypie e.g.: `pip install django-tastypie==0.14.2`

Found a workaround for the first issue by adding some code, but tastypie version did clash with API enable feature.

django-tastypie==0.14.0 would be the last supported version for Django 1.11 so I went with that one. Works like a charm for now. 

Thanks for the feedback!

**Comment by SlinkyLink** [comment]
> > Try to install older version of django-tastypie e.g.: `pip install django-tastypie==0.14.2`
> 
> Found a workaround for the first issue by adding some code, but tastypie version did clash with API enable feature.
> 
> django-tastypie==0.14.0 would be the last supported version for Django 1.11 so I went with that one. Works like a charm for now.
> 
> Thanks for the feedback!


@m-katunar @dionisimus 
Wow, how do you do force CRITs work, Im trying for some days. If some one solved those problems, pls contanct me.

**Comment by SlinkyLink** [comment]
> > > Try to install older version of django-tastypie e.g.: `pip install django-tastypie==0.14.2`
> > 
> > 
> > Found a workaround for the first issue by adding some code, but tastypie version did clash with API enable feature.
> > django-tastypie==0.14.0 would be the last supported version for Django 1.11 so I went with that one. Works like a charm for now.
> > Thanks for the feedback!
> 
> @m-katunar @dionisimus Wow, how do you do force CRITs work, Im trying for some days. If some one solved those problems, pls contanct me.

Solved.
- Use mongoengine 0.17

**Comment by johncrits** [comment]
Hi,

Sorry for the late reply
I am installed using sudo pip command the successful run's for me with same
version
