### ISSUE TITLE
Django 1.7 support

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#257]
Currently CRITs doesn't work under Django 1.7. I believe the issue is this change:

http://django.readthedocs.org/en/latest/releases/1.7.html (app-loading changes). More can be read here: http://django.readthedocs.org/en/latest/ref/applications.html

I get this when I try to start runserver:

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/mgoffin/git/crits/crits/crits/services/__init__.py", line 3, in <module>
    manager = svc_manager()
  File "/Users/mgoffin/git/crits/crits/crits/services/core.py", line 46, in __init__
    self._register_services(Service)
  File "/Users/mgoffin/git/crits/crits/crits/services/core.py", line 136, in _register_services
    new_config = service.get_config(existing_config)
  File "/Users/mgoffin/git/crits/crits_services/chopshop_service/__init__.py", line 46, in get_config
    fields = forms.ChopShopConfigForm().fields
  File "/Users/mgoffin/git/crits/crits_services/chopshop_service/forms.py", line 36, in __init__
    super(ChopShopConfigForm, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 122, in __init__
    self.label_suffix = label_suffix if label_suffix is not None else _(':')
  File "/usr/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 83, in ugettext
    return _trans.ugettext(message)
  File "/usr/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 325, in ugettext
    return do_translate(message, 'ugettext')
  File "/usr/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 306, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 209, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 189, in _fetch
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

Looks like the way we import services violates their new app-loading stuffs?

**Comment by dsnellgrove** [comment]
1.6 has now exited extended support (security fixes etc). 1.8 is now available and is also an LTS release so is more recommended than 1.7 if it works.

**Comment by mgoffin** [comment]
We still need to completely redo how services work if we are going to go past 1.6 to 1.7. I haven't been able to figure it out in my attempts thus far. I suspect the same problems will exist in 1.8 if we decide to make that huge of a jump.

**Comment by dsnellgrove** [comment]
Just suggesting 1.8 since support for 1.7 ends six months whereas 1.8 will be supported for three years. Any version that receives security updates is...nice to have.

**Comment by brlogan** [comment]
I'd love to see us use 1.8 if we can get it to work.

**Comment by frbapolkosnik** [comment]
There's two things that I've done to get through this... 
- As listed in https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/ I've added and populated TEMPLATES in crits/settings.py
- adding "kwargs.setdefault('label_suffix', ':')" before the super(someServiceForm) for every service, changes are in there: 
https://github.com/frbapolkosnik/crits_services/tree/django_1.8_fixes

**Comment by frbapolkosnik** [comment]
Digging further, django-tastypie is the source of another issue:

https://github.com/django-tastypie/django-tastypie/issues/1009

Here's the fix:

https://github.com/django-tastypie/django-tastypie/commit/59515720c94b97802cbb32904db549845f30cdae

**Comment by frbapolkosnik** [comment]
another thing that doesn't bode well in tastypie with django 1.8 is in resource.py.
commit_on_success() is gone in 1.8, and the closest thing to it is atomic()
so the change in tastypie's resource.py line 2190 should be:
@transaction commit_on_success() should be renamed to @transaction atomic()

**Comment by frbapolkosnik** [comment]
I'm stuck at:
Traceback:
File "/Library/Python/2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/adam/Downloads/crits_my/crits/crits/core/views.py" in login
  400.                               RequestContext(request))
File "/Library/Python/2.7/site-packages/django/template/context.py" in __init__
  209.             updates.update(processor(request))

Exception Type: ValueError at /login/
Exception Value: dictionary update sequence element #0 has length 0; 2 is required

**Comment by gtback** [comment]
+1 to @dsnellgrove and @brlogan . If it's worth making the jump to 1.7, going all the way to 1.8 is a better solution.

**Comment by frbapolkosnik** [comment]
I've got Django 1.7.11 running as long as the crits_services are not loaded. Great success! ;-)
https://github.com/frbapolkosnik/crits/tree/django_1.8_fixes

**Comment by mgoffin** [comment]
Man I wish we could find a better way to do services so they are loaded dynamically (and installed dynamically without web server restart) so we can do things like "Add a Service" in the UI.

**Comment by frbapolkosnik** [comment]
It looks like the login issue was solved by following the wisdom of the warning from Django 1,8: **(1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DEBUG.
**

Once I renamed them and added the right fields in TEMPLATES, it started working. Now the issue is that the menu is missing, and until I've added 'crits.config' to INSTALLED_APPS, the config was not showing.

**Comment by frbapolkosnik** [comment]
Turns out that having a decorator (@user_passes_test(user_can_view_data)) executing before "def user_context(request):", which turns out to be a template_context_processor is causing the last error, I guess they changed implementation in Django and it started causing issues in 1.7.

Anyway, my PRs (one for crits, and another one for crits_services) are in, and ererything is working on my test instance on OSX. Please take it for a spin, as for 1.8, it seems that getting 1.8 to run might be a bit harder with mongoengine split and all that.

**Comment by frbapolkosnik** [comment]
We have Django 1.7 in the master, and a PR that makes CRITs work on Django 1.8 now. I guess we can close this now.

**Comment by frbapolkosnik** [comment]
Are we going to close it, or keep it open for Django 1.9?

**Comment by mgoffin** [comment]
We can close and track 1.9 in a new Issue I guess :)
