### ISSUE TITLE
Domain bulk upload add IP Broken

### ISSUE THREAD

**Issue by craigh6247** [crits/crits#394]
There seems to be a issue with bulk uploading domains with associating IP. Bulk upload domain page table validates fine. Once uploaded status message says upload complete, when checking the domain testing.com has been uploaded but the IP has not been uploaded. 
crits.log records no errors. 
Apache error log:
Traceback (most recent call last):
File "/data/crits/crits/core/handsontable_tools.py", line 221, in parse_bulk_upload (result, errors, retVal) = add_new_function(data, rowData, request, errors, is_validate_only, cache)
File "/data/crits/crits/domains/handlers.py", line 249, in add_new_domain_via_bulk is_validate_only=is_validate_only, cache=cache)
File "/data/crits/crits/domains/handlers.py", line 343, in add_new_domain cache=cache)
File "/data/crits/crits/ips/handlers.py", line 360, in ip_add_update if "Address - ipv4" in ip_type:
typeError: argument of type 'NoneType' is not iterable

**Comment by thelok** [comment]
This happens on the single add domain form as well when trying to add both a domain and a IP.
