### ISSUE TITLE
Creating test user throws exception

### ISSUE THREAD

**Issue by krmaxwell** [crits/crits#435]
When creating a user, using a local domain appears to generate an exception. T

```
Creating indexes (duplicates will be ignored automatically)
Username: crits
First name: Test
Last name: User
Email address: crits@crits
Organization name: CRITs
Adding a default admin account
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/crits/crits/crits/core/management/commands/users.py", line 173, in handle
    user = CRITsUser.create_user(username, password, email)
  File "/home/crits/crits/crits/core/user.py", line 672, in create_user
    user.create_api_key("default", analyst, default=True)
  File "/home/crits/crits/crits/core/user.py", line 576, in create_api_key
    self.save(username=analyst)
  File "/home/crits/crits/crits/core/crits_mongoengine.py", line 361, in _custom_save
    _refs=_refs)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 224, in save
    self.validate(clean=clean)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 323, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (CRITsUser:None) (Invalid Mail-address: crits@crits: ['email'])
Make note of the above password so you can authenticate!
```

**Comment by mgoffin** [comment]
Hmm, yea. We should probably try to catch the user creation return code as well. Obviously the quick fix to this for you is to provide a valid email address if you need/want to get going before we fix that :)

**Comment by krmaxwell** [comment]
For my test instance, yes, I'm going to do that. But catching and handling the exception is good. Allowing local mail is also good!

**Comment by mgoffin** [comment]
It's MongoEngine validation, not our own custom one. We can try to create our own custom field for this, but it might be more effort than it's worth? I'm open to suggestions on it :)

**Comment by dsnellgrove** [comment]
There are other aspects of CRITs that demand a valid email address so the validation is good, I don't recommend hacking that. Handling the error is good if you think the error message "(Invalid Mail-address: crits@crits: ['email'])" isn't clear (the existence of this bug is evidence that it's unclear).

@krmaxwell Using the FQDN of the system rather than just the hostname should satisfy the parser. I think the presence of a dot somewhere in the domain is what it wants. It should work for your local mail handler (assuming you have one and it's configured correctly) for any notifications, password reset emails, etc for the user.
