### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by andyrat33** [crits/crits#440]
After the server started attempt to access it on http://serveraddress:8080 times and out and barfs:

[31/Mar/2015 17:47:03] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xae\x01\x00\x00\xaa\x03\x01U\x1b\x15\xd76\xff\x05]\xda')
----------------------------------------
Exception happened during processing of request from ('172.31.254.179', 53298)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 138, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 5: ordinal not in range(128)

it maybe that the install instructions are lacking.

**Comment by mgoffin** [comment]
I suspect it's not the instructions but an improper use of the web server. A quick google search shows this:

http://stackoverflow.com/questions/18940441/strange-unicodedecodeerror-on-django

I know you've stated that you are visiting "http" and not "https" but the errors are too similar not to suggest reviewing that post and serif if that's the problem.

**Comment by wxsBSD** [comment]
I haven't read the link @mgoffin posted but I know that \x16\x03\x01\x00 is a TLS 1.0 CLIENT HELLO, which is the first packet in a normal SSL handshake. This looks like your browser is trying to speak SSL to a server that doesn't speak SSL.
