### ISSUE TITLE
Database migrations for version upgrade stopping

### ISSUE THREAD

**Issue by sgerlach** [crits/crits#455]
When performing maintenance on or database items, occsionally they run for a long time and get "killed" 
```
$python manage.py upgrade -i -s
Killed
```

This happens on indicators, ips and domains. Is there a 'no timeout' setting or something or a mongo command that does the same?
and when I try to do 
```
$python manage.py upgrade -D -s
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/data/crits/crits/core/management/commands/upgrade.py", line 125, in handle
    upgrade(lv, options)
  File "/data/crits/crits/core/management/commands/upgrade.py", line 212, in upgrade
    migrate_collection(Domain, sort_ids)
  File "/data/crits/crits/core/management/commands/upgrade.py", line 151, in migrate_collection
    print "Migrating %ss...%d" % (class_obj._meta['crits_type'], len(docs))
  File "/data/crits/crits/core/crits_mongoengine.py", line 73, in __len__
    list(self._iter_results())
  File "/usr/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 81, in _iter_results
    self._populate_cache()
  File "/usr/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 93, in _populate_cache
    self._result_cache.append(self.next())
  File "/usr/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 1141, in next
    _auto_dereference=self._auto_dereference)
  File "/data/crits/crits/core/crits_mongoengine.py", line 430, in _from_son
    doc = super(CritsDocument, cls)._from_son(son, _auto_dereference)
  File "/usr/lib/python2.7/site-packages/mongoengine/base/document.py", line 570, in _from_son
    else field.to_python(value))
  File "/usr/lib/python2.7/site-packages/mongoengine/base/fields.py", line 254, in to_python
    for key, item in value.items()])
  File "/usr/lib/python2.7/site-packages/mongoengine/fields.py", line 551, in to_python
    return self.document_type._from_son(value)
  File "/usr/lib/python2.7/site-packages/mongoengine/base/document.py", line 587, in _from_son
    raise InvalidDocumentError(msg)
mongoengine.errors.InvalidDocumentError: Invalid data to create a `EmbeddedSource` instance.
instances - 'NoneType' object has no attribute 'get'
```

Would be nice to try and figure out that error as well. Thanks for the help all.

**Comment by dsnellgrove** [comment]
Add --traceback to manage.py so you can get a stack trace when it dies. The "Killed" statement makes me think the system killed it though due to memory exhaustion.

The latter error appears to be an invalid object. You may need to add some debugging to get the document ID when that happens to find which document in your database is malformed enough to make the command crash.

**Comment by sgerlach** [comment]
Turns out you were right on both counts. One bad DNS document and running out of memory after processing sooo many schema upgrades on indicators.

**Comment by dsnellgrove** [comment]
Disabling queryset caching might prevent the out of memory issue for the upgrade otherwise iterating over a large mongengine query takes progressively more memory. That's an option in the CRITs settings database as I recall which the migrate script might follow.

**Comment by sgerlach** [comment]
Right again! Much better performance on the upgrade scripts with query caching turned off. I totally forgot about that setting.

**Comment by dsnellgrove** [comment]
So to turn this into a feature request, looks like two things:

1) override the query caching setting in the upgrade script somehow, caching isn't just slower it's also dangerous (can cause an unexpected crash part way through) in this case.
2) better exception catching so if a document upgrade blows up a more useful error message and indication of which document was a problem so users can troubleshoot themselves (document blah failed at blerg with error suchandsuch. Please correct any abnormalities in the structure of blah before restarting the upgrade)

**Comment by sgerlach** [comment]
I think this sounds right. A lot of the errors you get from the upgrade script are very generic and don't necessarily point out the document that is causing the issue.
