### ISSUE TITLE
Bootstrab script fails

### ISSUE THREAD

**Issue by seanthegeek** [crits/crits#472]
Dependency installations complete!
Setting up crits.log file
Creating default database configuration file
sed: can't read : No such file or directory
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/crits/crits/crits/core/management/commands/create_default_collections.py", line 8, in <module>
    from create_event_types import add_event_types
  File "/home/crits/crits/crits/core/management/commands/create_event_types.py", line 3, in <module>
    from crits.events.event import EventType
  File "/home/crits/crits/crits/events/event.py", line 7, in <module>
    from crits.core.crits_mongoengine import CritsSchemaDocument, CritsBaseAttributes
  File "/home/crits/crits/crits/core/crits_mongoengine.py", line 23, in <module>
    from mongoengine import QuerySetNoCache as QS
ImportError: cannot import name QuerySetNoCache

**Comment by mgoffin** [comment]
Please review other open issues before posting duplicates.
