### ISSUE TITLE
msg upload  fails

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#556]
crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n', '  File "/data/crits/crits/emails/views.py", line 434, in email_outlook_add\n    campaign_confidence)\n', '  File "/data/crits/crits/emails/handlers.py", line 792, in handle_msg\n    mimetype = magic.from_buffer(file[\'data\'], mime=True)\n', "KeyError: 'data'\n"]

Email contains a long-ish thread, and .eml is in attachment

**Comment by frbapolkosnik** [comment]
I think that this should be reworked to upload the attachments as raw.

**Comment by frbapolkosnik** [comment]
I turns out that (2.2.2.1) Embedded Message Object Storage support needs to be added to the code in CRITs in order to handle attached emails.

http://download.microsoft.com/download/5/D/D/5DD33FDF-91F5-496D-9884-0A0B0EE698BB/[MS-OXMSG].pdf

**Comment by frbapolkosnik** [comment]
Just to provide an update, I've already have some code for it, but some parts of the code need to be reworked to process and to add/relate the attached emails
