### ISSUE TITLE
no module named django

### ISSUE THREAD

**Issue by affvei** [crits/crits#621]
$ sh script/bootstrap 4
Database configuration file exists, skip secret_key generation!
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django

$ python -c "import django; print(django.get_version())"
1.8.5

**Comment by frbapolkosnik** [comment]
Is that master or stable-4?  Was that cloned from github or some other way?

**Comment by frbapolkosnik** [comment]
You need to have django 1.6.x, anything higher than 1.6 is not working at the moment.

**Comment by affvei** [comment]
I uninstall 1.8 and installed django 1.6 and now I'm getting this error:
ImportError: No module named django.mongo_auth

**Comment by frbapolkosnik** [comment]
grab the requirements.txt file from master branch on github, and use it to install the dependencies

**Comment by frbapolkosnik** [comment]
err... actually grab scripts/bootstrap too and run it.

**Comment by affvei** [comment]
When I do that I get this:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named django.mongo_auth

Error: To restart at this step: sh script/bootstrap 4

**Comment by frbapolkosnik** [comment]
What distro are you installing this on?

**Comment by affvei** [comment]
Ubuntu server 14.04

**Comment by frbapolkosnik** [comment]
Which branch of CRITs are you trying to install?

**Comment by affvei** [comment]
Master

**Comment by frbapolkosnik** [comment]
ok... start from scratch?

git clone https://github.com/crits/crits.git
cd crits
sh ./script/bootstrap

**Comment by affvei** [comment]
I get this:

Dependency installations complete!
Mongo already installed
mode of ‘/data’ retained as 0755 (rwxr-xr-x)
mode of ‘/data/db’ retained as 0755 (rwxr-xr-x)
mode of ‘/data/logs’ retained as 0755 (rwxr-xr-x)
Database configuration file exists, skip secret_key generation!
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named django.mongo_auth

**Comment by frbapolkosnik** [comment]
if it still breaks try pip install -U -r requirements.txt

**Comment by affvei** [comment]
Ok, I tried it like you said but when I continue the script...

eita@giovana:~/crits$ sh script/bootstrap 4
Database configuration file exists, skip secret_key generation!
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named django.mongo_auth

**Comment by mgoffin** [comment]
I'd have to assume there's an issue with installing mongoengine or it's
being clobbered with the tastypie-mongoengine stuff (we've had this happen
before). Can you make sure mongoengine is installed via `pip install
mongoengine==0.8.7`

**Comment by affvei** [comment]
I make the pip installation as you said but, again, another error..

$ sh script/bootstrap 4
Database configuration file exists, skip secret_key generation!
Creating default collections
Exception AttributeError: "'Cursor' object has no attribute '_Cursor__id'" in <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x7f909abed2d0>> ignored
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/eita/crits/crits/services/__init__.py", line 3, in <module>
    manager = svc_manager()
  File "/home/eita/crits/crits/services/core.py", line 46, in __init__
    self._register_services(Service)
  File "/home/eita/crits/crits/services/core.py", line 165, in _register_services
    for svc in svcs:
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/queryset.py", line 156, in __iter__
    queryset.rewind()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1153, in rewind
    self._cursor.rewind()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1183, in _cursor
    **self._cursor_args)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 929, in find
    return Cursor(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'snapshot'

**Comment by frbapolkosnik** [comment]
I just spun up a fresh vm with ubuntu 14.04.2 to test, it fails on pymongo missing... It looks like we'll need to fix some things up due to upstream changes.

**Comment by affvei** [comment]
it fails with various things like M2Crypt, magic, pymongo.

**Comment by affvei** [comment]
Well, I pymongo downgraded to 2.8 (was 3.0.3) and it worked, but it comes with a new error:

  File "/home/eita/crits/crits/core/user.py", line 75, in EmbeddedSubscription
    date = DateTimeField(default=datetime.datetime.now)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

**Comment by affvei** [comment]
Well, I pymongo downgraded to 2.8 (was 3.0.3) and it worked, but it comes with a new error:

from PIL import Image
ImportError: No module named PIL

**Comment by frbapolkosnik** [comment]
ok, try this... 
sudo apt-get install m2crypto

then run the 
script/bootstrap

**Comment by affvei** [comment]
I Already managed to pass several errors as the m2crypto and magic. The problem now is with
```
from PIL import Image
ImportError: No module named PIL
```

**Comment by frbapolkosnik** [comment]
pip install -U 'Pillow<3.0'   ?

**Comment by affvei** [comment]
ITS WORKINGS!!

I builded from source, after that i got an error at import olefile, just made a pip install olefile and now it is working!

Thank you guys. Love CRITs, Love you.
Lets celebrate with a party haha

**Comment by frbapolkosnik** [comment]
Good job, thanks for not giving up!

**Comment by affvei** [comment]
One last help if not too uncomfortable, please.
```
$ python manage.py setconfig service_dirs "/data/crits_services"
A CRITs configuration already exists. Skipping default creation.
CommandError: Not a valid path: /data/crits_services
```
But I do have those folders

**Comment by frbapolkosnik** [comment]
/data/crits/crits/core/management/commands/setconfig.py is where check happens. I can't replicate unless I point it to the non-existing path.

**Comment by affvei** [comment]
python manage.py setconfig service_dirs "/data/crits_services"

I just need to cut the first /
```
python manage.py setconfig service_dirs "data/crits_services"
```
