### ISSUE TITLE
Setup script fails to install on CentOS 6.6

### ISSUE THREAD

**Issue by iankronquist** [crits/crits#631]
The setup script fails to install on CentOS 6.6. I suspect some libjpeg dependency is missing.

I used this vagrant file:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "puppetlabs/centos-6.6-64-nocm"
end

```

```
Installing Python Dependencies
Collecting Django<1.7 (from -r requirements.txt (line 1))
  Downloading Django-1.6.11-py2.py3-none-any.whl (6.7MB)
    100% |████████████████████████████████| 6.7MB 94kB/s 
Collecting Pillow (from -r requirements.txt (line 2))
  Downloading Pillow-3.0.0.tar.gz (9.6MB)
    100% |████████████████████████████████| 9.6MB 62kB/s 
Collecting amqp (from -r requirements.txt (line 3))
  Downloading amqp-1.4.7.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 3.5MB/s 
Collecting anyjson (from -r requirements.txt (line 4))
  Downloading anyjson-0.3.3.tar.gz
Collecting billiard (from -r requirements.txt (line 5))
  Downloading billiard-3.3.0.21.tar.gz (151kB)
    100% |████████████████████████████████| 151kB 3.6MB/s 
Collecting biplist (from -r requirements.txt (line 6))
  Downloading biplist-0.9.tar.gz
Collecting celery (from -r requirements.txt (line 7))
  Downloading celery-3.1.19-py2.py3-none-any.whl (517kB)
    100% |████████████████████████████████| 520kB 1.1MB/s 
Collecting defusedxml (from -r requirements.txt (line 8))
  Downloading defusedxml-0.4.1.tar.gz (48kB)
    100% |████████████████████████████████| 49kB 6.5MB/s 
Collecting django-celery (from -r requirements.txt (line 9))
  Downloading django-celery-3.1.17.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 5.2MB/s 
Collecting django-tastypie==0.11.0 (from -r requirements.txt (line 10))
  Downloading django_tastypie-0.11.0-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 77kB 5.9MB/s 
Collecting django-tastypie-mongoengine==0.4.5 (from -r requirements.txt (line 11))
  Downloading django-tastypie-mongoengine-0.4.5.tar.gz (44kB)
    100% |████████████████████████████████| 45kB 5.9MB/s 
Collecting kombu (from -r requirements.txt (line 12))
  Downloading kombu-3.0.29-py2.py3-none-any.whl (241kB)
    100% |████████████████████████████████| 241kB 2.5MB/s 
Collecting lxml (from -r requirements.txt (line 13))
  Downloading lxml-3.4.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 178kB/s 
Collecting m2crypto (from -r requirements.txt (line 14))
  Downloading M2Crypto-0.22.5.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 5.1MB/s 
Collecting mongoengine==0.8.7 (from -r requirements.txt (line 16))
  Downloading mongoengine-0.8.7.tgz (337kB)
    100% |████████████████████████████████| 339kB 1.7MB/s 
Collecting pydeep==0.2 (from -r requirements.txt (line 17))
  Downloading pydeep-0.2.tar.gz
Collecting pymongo==2.7.2 (from -r requirements.txt (line 18))
  Downloading pymongo-2.7.2.tar.gz (381kB)
    100% |████████████████████████████████| 385kB 1.5MB/s 
Collecting pyparsing (from -r requirements.txt (line 19))
  Downloading pyparsing-2.0.3-py2.py3-none-any.whl
Collecting python-dateutil (from -r requirements.txt (line 20))
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 192kB 2.8MB/s 
Collecting python-ldap (from -r requirements.txt (line 21))
  Downloading python-ldap-2.4.22.tar.gz (121kB)
    100% |████████████████████████████████| 122kB 4.4MB/s 
Collecting python-magic==0.4.6 (from -r requirements.txt (line 22))
  Downloading python-magic-0.4.6.tar.gz
Collecting python-mimeparse (from -r requirements.txt (line 23))
  Downloading python-mimeparse-0.1.4.tar.gz
Collecting pytz (from -r requirements.txt (line 24))
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 479kB 1.3MB/s 
Collecting pyyaml (from -r requirements.txt (line 25))
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 295kB/s 
Collecting requests (from -r requirements.txt (line 26))
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 1.2MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Collecting simplejson (from -r requirements.txt (line 28))
  Downloading simplejson-3.8.0.tar.gz (75kB)
    100% |████████████████████████████████| 77kB 5.7MB/s 
Collecting six (from -r requirements.txt (line 29))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting ushlex (from -r requirements.txt (line 30))
  Downloading ushlex-0.99.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wsgiref in /usr/lib64/python2.7 (from -r requirements.txt (line 31))
Collecting olefile (from -r requirements.txt (line 32))
  Downloading olefile-0.42.1.zip (119kB)
    100% |████████████████████████████████| 122kB 4.3MB/s 
Installing collected packages: Django, Pillow, amqp, anyjson, billiard, biplist, pytz, kombu, celery, defusedxml, django-celery, six, python-dateutil, python-mimeparse, django-tastypie, pymongo, mongoengine, lxml, pyyaml, django-tastypie-mongoengine, m2crypto, pydeep, pyparsing, python-ldap, python-magic, requests, simplejson, ushlex, olefile
  Running setup.py install for Pillow
    Complete output from command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-5I4wK2/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PG1JWU-record/install-record.txt --single-version-externally-managed --compile:
    Single threaded build, not installing mp_compile:1 processes
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-2.7/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5I4wK2/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/tmp/pip-build-5I4wK2/Pillow/setup.py", line 515, in build_extensions
        % (f, f))
    ValueError: --enable-jpeg requested but jpeg not found, aborting.
    
    ----------------------------------------
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-5I4wK2/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PG1JWU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5I4wK2/Pillow
Dependency installation failed!

        If M2Crypto failed to install, you might try to install the 
        OS-provided package with the package manager (apt-get/yum/brew)
        or try to use pip to install a fixed version from git by:
        pip install git+https://github.com/martinpaljak/M2Crypto.git
[vagrant@10-0-2-15 crits]$ 

```

**Comment by frbapolkosnik** [comment]
Yup, looks like Pillow wants the devel package for libjpeg

**Comment by tkinkead** [comment]
Also seeing this issue on Ubuntu 14.04.  Installing libjpeg-dev fixed the issue; it should likely be added as a required dependency.

**Comment by xg5-simon** [comment]
Confirmed the same behavior as tkinkhead

**Comment by action09** [comment]
Same here with Ubuntu 14.04 LTS ...
$ sudo aptitude install m2crypto libjpeg-dev
