### ISSUE TITLE
raw_data upload issues

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#633]
Two issues it seems:

One, I was trying to upload a new version of a raw_data document (from the web interface - "Upload New Version" ) and I got this:
```
DEBUG 2015-10-28 15:10:04,970 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n', '  File "/data/crits/crits/raw_data/views.py", line 380, in upload_raw_data\n    ticket=ticket)\n', '  File "/data/crits/crits/raw_data/handlers.py", line 356, in handle_raw_data_file\n    md5 = hashlib.md5(data).hexdigest()\n', "UnicodeEncodeError: 'ascii' codec can't encode characters in position 3907-3908: ordinal not in range(128)\n"]
```
Trying to quickly alleviate the issue, I replaced "data" with "data.encode('utf-8')". I'm curious if the data should be processed in some way earlier in upload_raw_data()? 
Perhaps data = request.POST.get('data', None) should be turned into data = form.cleaned_data.get('data', None) ?

The next thing, I got was the following (copy relationships checkbox was checked)

```
DEBUG 2015-10-28 15:23:45,579 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n', '  File "/data/crits/crits/raw_data/views.py", line 380, in upload_raw_data\n    ticket=ticket)\n', '  File "/data/crits/crits/raw_data/handlers.py", line 403, in handle_raw_data_file\n    rel_item = class_from_id(rel.rel_type, rel.rel_object_id)\n', "AttributeError: 'EmbeddedRelationship' object has no attribute 'rel_object_id'\n"]
```

When I unchecked the copy relationships checkbox everything went ok.

**Comment by mgoffin** [comment]
I think we had a PR recently that removed the decode in raw_data. Someone noted it was causing issues. Now it seems to be back to the original reason why I had it in there in the first place?

**Comment by frbapolkosnik** [comment]
lol, I've focused on fixing the second issue, perhaps someone else can chime in here.
