### ISSUE TITLE
Migrating samples in stable

### ISSUE THREAD

**Issue by Magicked** [crits/crits#651]

**Comment by Magicked** [comment]
Oops, accidentally hit enter as I was typing the title... 

This seems to be related to django indexes. Any suggestions?

$ python manage.py upgrade -S
Drop protection does not apply to sector objects
Added 16 Sector Objects.
Creating indexes (duplicates will be ignored automatically)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/crits/crits/crits/core/management/commands/upgrade.py", line 137, in handle
    upgrade(lv, options)
  File "/home/crits/crits/crits/core/management/commands/upgrade.py", line 216, in upgrade
    prep_database()
  File "/home/crits/crits/crits/core/management/commands/prep.py", line 180, in prep_database
    prep_indexes()
  File "/home/crits/crits/crits/core/management/commands/prep.py", line 165, in prep_indexes
    create_indexes()
  File "/home/crits/crits/crits/core/management/commands/create_indexes.py", line 144, in create_indexes
    notifications.ensure_index("obj_id", background=True)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 958, in ensure_index
    return self.create_index(key_or_list, cache_for, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 863, in create_index
    **self._get_wc_override())
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
  File "/usr/lib/python2.7/dist-packages/pymongo/message.py", line 248, in _do_batched_insert
    client._send_message(_insert_message(EMPTY.join(data), safe), safe)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 969, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 911, in __check_response_to_last_error
    raise OperationFailure(details["err"], details["code"])
pymongo.errors.OperationFailure: Index with name: obj_id_1 already exists with different options

**Comment by mgoffin** [comment]
If you do -Ss it will skip the prep. I suspect, though, that you have an
old index with options that MongoEngine is trying to add and it can't.
There are entries in the UPDATING file which I think cover this and might
help.

**Comment by Magicked** [comment]
Ah, the fix was easy enough. I had an old index as you suggested. This line was the key:

File "/home/crits/crits/crits/core/management/commands/create_indexes.py", line 144, in create_indexes
notifications.ensure_index("obj_id", background=True)

I went into the mongo shell and did:

db.notifications.dropIndex( "obj_id_1" )

Then it ran fine. Thanks!

**Comment by mgoffin** [comment]
No problem :)
