### ISSUE TITLE
Error uploading file on Microsoft Outlook .MSG File

### ISSUE THREAD

**Issue by myntric** [crits/crits#660]
We have had a significant increase in phish messages arriving that contain embedded code that CRITs seems to fail processing each time.  Below is a snippet of the error code logged with Apache2.  This has been an ongoing issue for awhile.  

Mon Nov 23 10:12:37.743647 2015] [:error] [pid 8527:tid 140503714576128] 3092311 ERROR: Internal Server Error: /emails/new/outlook/
[Mon Nov 23 10:12:37.743816 2015] [:error] [pid 8527:tid 140503714576128] Traceback (most recent call last):
[Mon Nov 23 10:12:37.743888 2015] [:error] [pid 8527:tid 140503714576128]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
[Mon Nov 23 10:12:37.743898 2015] [:error] [pid 8527:tid 140503714576128]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Nov 23 10:12:37.743905 2015] [:error] [pid 8527:tid 140503714576128]   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Mon Nov 23 10:12:37.743912 2015] [:error] [pid 8527:tid 140503714576128]     return view_func(request, *args, **kwargs)
[Mon Nov 23 10:12:37.743918 2015] [:error] [pid 8527:tid 140503714576128]   File "/data/crits/crits/emails/views.py", line 444, in email_outlook_add
[Mon Nov 23 10:12:37.743925 2015] [:error] [pid 8527:tid 140503714576128]     ticket)
[Mon Nov 23 10:12:37.743951 2015] [:error] [pid 8527:tid 140503714576128]   File "/data/crits/crits/emails/handlers.py", line 783, in handle_msg
[Mon Nov 23 10:12:37.743959 2015] [:error] [pid 8527:tid 140503714576128]     result = parse_ole_file(data)
[Mon Nov 23 10:12:37.743966 2015] [:error] [pid 8527:tid 140503714576128]   File "/data/crits/crits/emails/handlers.py", line 1518, in parse_ole_file
[Mon Nov 23 10:12:37.743973 2015] [:error] [pid 8527:tid 140503714576128]     email['raw_body'] = get_stream_data(entry).decode('utf-16')
[Mon Nov 23 10:12:37.743980 2015] [:error] [pid 8527:tid 140503714576128]   File "/usr/lib/python2.7/encodings/utf_16.py", line 16, in decode
[Mon Nov 23 10:12:37.743988 2015] [:error] [pid 8527:tid 140503714576128]     return codecs.utf_16_decode(input, errors, True)
[Mon Nov 23 10:12:37.743994 2015] [:error] [pid 8527:tid 140503714576128] UnicodeDecodeError: 'utf16' codec can't decode bytes in position 2-3: illegal encoding

**Comment by frbapolkosnik** [comment]
what happens when you change
```
email['raw_body'] = get_stream_data(entry).decode('utf-16')
```
 to
```
email['raw_body'] = get_stream_data(entry)
```
?

**Comment by frbapolkosnik** [comment]
Try also this one:
```
email['raw_body'] = get_stream_data(entry).decode('utf-16-le')
```

**Comment by myntric** [comment]
Thanks Adam!

After removing the decoding part from /data/crits/crits/emails/handler.py
it seems to resolve the issue.  The e-mail uploaded successfully and
extracted the data fields.  I've tested several others that were failing
and all have been successful as well.

**Comment by frbapolkosnik** [comment]
Glad to hear that it worked. I'll probably create a PR for this change once I'll try to find some docs spelling out the encoding.

**Comment by myntric** [comment]
While it worked with English e-mails, it did not work with ones containing
Chinese character sets, such as the below.  I'd imagine this would hold
true with other foreign language characters as well.

*发件人**:* Customer Protection
*发送时间:* 2015年11月24日 1:11
*收件人:* s <no-reply@email.com>ample@email.com
*主题:* Protect Your Account


Failed to save object.

strings in documents must be valid UTF-8: 'P\x00l\x00e\x00a\x00s\x00e\x00

**Comment by apolkosnik** [comment]
Try going back to the original, and change 'utf-16' to 'utf-8' in that
decode

**Comment by myntric** [comment]
Back to the error:

[Mon Nov 30 10:34:09.111361 2015] [:error] [pid 18538:tid 139994710595328]
Traceback (most recent call last):
[Mon Nov 30 10:34:09.111370 2015] [:error] [pid 18538:tid 139994710595328]
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py",
line 112, in get_response
[Mon Nov 30 10:34:09.111376 2015] [:error] [pid 18538:tid 139994710595328]
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Nov 30 10:34:09.111382 2015] [:error] [pid 18538:tid 139994710595328]
  File
"/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line
22, in _wrapped_view
[Mon Nov 30 10:34:09.111388 2015] [:error] [pid 18538:tid 139994710595328]
    return view_func(request, *args, **kwargs)
[Mon Nov 30 10:34:09.111394 2015] [:error] [pid 18538:tid 139994710595328]
  File "/data/crits/crits/emails/views.py", line 444, in email_outlook_add
[Mon Nov 30 10:34:09.111400 2015] [:error] [pid 18538:tid 139994710595328]
    ticket)
[Mon Nov 30 10:34:09.111444 2015] [:error] [pid 18538:tid 139994710595328]
  File "/data/crits/crits/emails/handlers.py", line 783, in handle_msg
[Mon Nov 30 10:34:09.111454 2015] [:error] [pid 18538:tid 139994710595328]
    result = parse_ole_file(data)
[Mon Nov 30 10:34:09.111460 2015] [:error] [pid 18538:tid 139994710595328]
  File "/data/crits/crits/emails/handlers.py", line 1516, in parse_ole_file
[Mon Nov 30 10:34:09.111479 2015] [:error] [pid 18538:tid 139994710595328]
    email['subject'] = get_stream_data(entry).decode('utf-8')
[Mon Nov 30 10:34:09.111486 2015] [:error] [pid 18538:tid 139994710595328]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
[Mon Nov 30 10:34:09.111492 2015] [:error] [pid 18538:tid 139994710595328]
    return codecs.utf_8_decode(input, errors, True)
[Mon Nov 30 10:34:09.111498 2015] [:error] [pid 18538:tid 139994710595328]
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 1:
invalid start byte

**Comment by frbapolkosnik** [comment]
Can you try 'utf-16le'?

**Comment by dsnellgrove** [comment]
What version of olefile is installed? Versions prior to v41 only supported the latin1 character set (this was fixed as part of their update for python 3.x support they did late last year).  If it's v41+ the data in streams are encoded with utf8 (not 16 or 16le) in the OleFileIO object, though I think this might assume the object was totally created with olefile. If you want to get unicode straight out instead of decoding it try changing ```ole = olefile.OleFileIO(msg_file)``` to ```ole = olefile.OleFileIO(msg_file, path_encoding=None)``` and remove the .decode() methods called on the get_stream_data() methods.

Disclaimer: Everything I know about olefile and its stream encoding I just read on https://bitbucket.org/decalage/olefileio_pl/wiki/API over lunch.

**Comment by myntric** [comment]
Adam,

It took awhile, but I believe I figured out a workaround with the
decoding.  I made the following code changes nearly 8 months ago and have
not had any issues uploading emails (thousands) since.

diff /data/backup/crits/emails/handlers.py handlers.py
1592c1592
<                 email['subject'] =
get_stream_data(entry).decode('utf-16',errors='ignore')
---
>                 email['subject'] = get_stream_data(entry).decode('utf-16')
1594c1594
<                 email['raw_body'] =
get_stream_data(entry).decode('utf-16',errors='ignore')
---
>                 email['raw_body'] =
get_stream_data(entry).decode('utf-16')
1596c1596
<                 email['raw_header'] =
get_stream_data(entry).decode('utf-16',errors='ignore')
---
>                 email['raw_header'] =
get_stream_data(entry).decode('utf-16')
1598c1598
<
email['to'].append(get_stream_data(entry).decode('utf-16',errors='ignore').lower())
---
>
email['to'].append(get_stream_data(entry).decode('utf-16').lower())
1600c1600
<                 message_class =
get_stream_data(entry).decode('utf-16',errors='ignore').lower()
---
>                 message_class =
get_stream_data(entry).decode('utf-16').lower()

I believe there were certain characters contained within the email that
couldn't be processed with utf-16, but by ignoring errors in the data
stream it seems to work.

Mike

**Comment by apolkosnik** [comment]
Looking at MS-OXMSG documentation...

2.1.1.1 PidTagStoreSupportMask
Type: PtypInteger32 ([MS-OXCDATA] section 2.11.1)
The PidTagStoreSupportMask property ([MS-OXPROPS] section 2.1020) indicates whether string properties within the .msg file are Unicode-encoded or not. This property defines multiple flags, but only the STORE_UNICODE_OK flag is valid. All other bits MUST be ignored. The settings for this property are summarized in the following table.
```
Flag name            Value                          Description
STORE_UNICODE_OK     0x00040000                     Set if the string properties are Unicode-encoded.
other flags          All values except 0x00040000   All other bits MUST be ignored.
```
