### ISSUE TITLE
Unable to post targets through the API

### ISSUE THREAD

**Issue by anonjondoe** [crits/crits#661]
Able to post IP's through a python script using the API

>import requests
>url = 'https://localhost/api/v1/ips/'
>data = {
>'api_key': '(api_key)',
>'username': '(username)',
>'campaign': '(valid_campaign)',
>'ip': '(ip_address)',
>'ip_type': '(IPv4 Address)',
>'source': '(source)',
>'confidence': 'low'
>}
>r=requests.post(url=url, data=data, verify=False)
>print r.status_code

But cannot post Targets

>import requests
>url = 'https://localhost/api/v1/targets/'
>data = {
>'api_key': '(api_key)',
>'username': '(username)',
>'campaign': '(valid_campain)',
>'confidence': 'low',
>'firstname': 'NA',
>'lastname': 'NA',
>'division': 'NA',
>'organization_id': 'NA',
>'title': 'NA',
>'note': 'NA',
>'email_address': '(email_address)',
'source': '(source)',
'method': 'email',
'reference': 'NA',
'ticket': 'NA',
'bucket_list': 'NA'
}
r = requests.post(url=url, data=data, verify=False)
print r.status_code

**Comment by johnfellers** [comment]
I tested this and it works.. Even with the invalid fields that are not relevant to Targets.
These are invalid fields for posting Targets:
'confidence': 'low',
'source': '(source)',
'method': 'email',
'reference': 'NA',

Also if you check your HTTP error logs or CRITs error log it should give you a clue as to why it failed.
Can you post the result of 'print r.status_code' after you execute your requests.post?

Can you post your error logs from CRITs and from your webserver?

**Comment by ckane** [comment]
I see this too, on the current git master I updated just tonight. The following error is given:
<pre>Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 201, in wrapper
    response = callback(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 432, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/tastypie_mongoengine/resources.py", line 430, in dispatch
    return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))

  File "/usr/local/lib/python2.7/site-packages/tastypie_mongoengine/resources.py", line 393, in _wrap_request
    return fun()

  File "/usr/local/lib/python2.7/site-packages/tastypie_mongoengine/resources.py", line 430, in <lambda>
    return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))

  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 464, in dispatch
    response = method(request, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1342, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))

  File "/data/crits/crits/targets/api.py", line 51, in obj_create
    result = upsert_target(data, analyst)

  File "/data/crits/crits/targets/handlers.py", line 106, in upsert_target
    if related_id:

UnboundLocalError: local variable 'related_id' referenced before assignment</pre>

**Comment by ckane** [comment]
Dropped a fix in PR #736 - can you tell me if that fixes your problem too?
