### ISSUE TITLE
CRITS install issues - pip

### ISSUE THREAD

**Issue by tmorgan3** [crits/crits#856]
Running into a few issues trying to install CRITS on a new Ubuntu VM 16.04. Do I need to upgrade version of pip to resolve this? Thanks

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Dependency installation failed!

        If M2Crypto failed to install, you might try to install the 
        OS-provided package with the package manager (apt-get/yum/brew)
        or try to adjust the CFLAGS, LDFLAGS, and SWIG_FEATURES
        with the right path to openssl headers and libs:
        sudo -E env LDFLAGS="-L/opt/local/lib"                     CFLAGS="-I/opt/local/include"                     SWIG_FEATURES="-cpperraswarn -includeall -I/opt/local/include"                     pip install M2Crypto

**Comment by apolkosnik** [comment]
Yes

**Comment by tmorgan3** [comment]
Thanks. I ran an 

'apt-get update'
'apt-get upgrade'

and are still pulling down 8.1..1 when 'apt-get install python-pip' is run. Any suggestions on how to download\install 9.0.1? Even 'apt-get install python-pip=9.0.1' gives me 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '9.0.1' for 'python-pip' was not found

Not doing something right. Any suggestions??

**Comment by apolkosnik** [comment]
sudo pip install --upgrade pip

**Comment by tmorgan3** [comment]
>sudo -H pip install --upgrade pip
Requirement already up-to-date: pip in /usr/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by apolkosnik** [comment]
It is a pip issue

**Comment by jreegun** [comment]
Faced the exact issue, below is the fix

In terminal
_wget https://bootstrap.pypa.io/get-pip.py_
_python get-pip.py_

then start the installation again.
