### ISSUE TITLE
problem domain record?

### ISSUE THREAD

**Issue by mallorybobalice** [crits/crits#873]
Hi,

was wondering if we could get a hand diagnosing the problem.Don't have access to the linux side logs , but will pass these to the ops guys that do.

noticed a missing chunk in domains
https://xxxx/api/v1/domains/?offset=7040&limit=1&format=xml&username=collection&api_key=yyyy
````
error 500 -internal server error 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<error_message>
Invalid data to create a `EmbeddedSource` instance. instances - 'NoneType' object has no attribute 'get'
</error_message>
<traceback>
Traceback (most recent call last): File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/tastypie/resources.py", line 219, in wrapper response = callback(request, *args, **kwargs) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/tastypie/resources.py", line 450, in dispatch_list return self.dispatch('list', request, **kwargs) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/tastypie_mongoengine/resources.py", line 426, in dispatch return super(MongoEngineResource, self).dispatch(request_type, request, **kwargs) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/tastypie/resources.py", line 482, in dispatch response = method(request, **kwargs) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/tastypie/resources.py", line 1340, in get_list for obj in to_be_serialized[self._meta.collection_name] File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 81, in _iter_results self._populate_cache() File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 93, in _populate_cache self._result_cache.append(self.next()) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 1141, in next _auto_dereference=self._auto_dereference) File "/data/crits/crits/core/crits_mongoengine.py", line 427, in _from_son doc = super(CritsDocument, cls)._from_son(son, _auto_dereference) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/base/document.py", line 570, in _from_son else field.to_python(value)) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/base/fields.py", line 254, in to_python for key, item in value.items()]) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/fields.py", line 551, in to_python return self.document_type._from_son(value) File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/mongoengine/base/document.py", line 587, in _from_son raise InvalidDocumentError(msg) InvalidDocumentError: Invalid data to create a `EmbeddedSource` instance. instances - 'NoneType' object has no attribute 'get'
</traceback>
</response>
````

same via 
(500) internal server error
via the ui get the same issue when going via domains/list/ (page 16,500 per page)
jtlststartindex=7500,&jtpagesize=500

any ideas how to diagnose and or delete the problem record from the db (and errr find it).

**Comment by mgoffin** [comment]
This would be a question for the mailing list. However, it seems you have a malformed "source" record in your database. Querying for "source: null" or "source: {$exists:0}" in mongo shell should find the culprit.

**Comment by mallorybobalice** [comment]
thanks for the quick response.appreciate it given this isn't really a bug. 
=) mailing list is too hard . this learning new things thing...
would you mind posting the full db.collection find syntax for the uninitiated along with the update syntax example if at all possible (mongo is more or less living hell)

**Comment by mgoffin** [comment]
Not at a computer at the moment but it is something like:

db.domains.findOne({"$or": [{"source": null}, {"source": {"$exists": 0}]})

If you find that it doesn't have a source record, it would be worth just removing it and re-adding by changing the "findOne" to "remove". If it has a null value you can do something like:

db.domains.update({"source": null}, {"$pull: {"source.$"}})

Note: these are untested and I highly suggest familiarizing yourself with MongoDB and mongo shell before doing stuff like this. Blindly running commands strangers tell you to run is bad if you don't understand what they are doing and cannot formulate them on your own.

**Comment by mallorybobalice** [comment]
thanks =) will mongodump or snapshot first... 
not very familiar with the document structure and the domain collection or dependencies re source (presume it's the intel source column).I might well remove it,but what's 

db.domains.update({"source": null}, {"$pull: {"source.$"}})

pull source bits?

**Comment by mgoffin** [comment]
Yea, the `$` is a positional, so the query is basically "find a document with a source list that has a "null" in one of the positions", and the update is "pull the entry at that position".

**Comment by mallorybobalice** [comment]
oic as in pull removes the source field from the doc with the null source field?

**Comment by mgoffin** [comment]
If you are saying what I think you are, then yes. Basically if you have this:

```
{
    "source": [
        "foo": "bar",
        null,
        "bar": "baz"
    ]
}
```

It would detect "null" at the second position in the list, and then the update would remove what is in position two, resulting in:

```
{
    "source": [
        "foo": "bar",
        "bar": "baz"
    ]
}
```

**Comment by mallorybobalice** [comment]
hmmm well, thanks again - close enough. 


db.domains.find( {"source.instances": null}).pretty() 

(wasn't source null). 

removed all the offending domains and subdomains (126 all for the same supra, all a really old advisory).... 
hopefully db.domains.remove({"domain":/.*sudomain.com.*/}) is safe-ish ?
