### ISSUE TITLE
The translation infrastructure cannot be initialized...

### ISSUE THREAD

**Issue by Tom-Gorup** [crits/crits#877]
I'm having an issue running `sh script/bootstrap`. I had crits installed previous, but it was project that fell off. In an attempt to bring the project back I'm running across some issues. I did a `git pull` and saw the updated pull, but I'm hitting a wall when attempting to stand back up.

Appreciate any assistance you can provide.

```
# sh script/bootstrap
Testing Computer's Architecture
Architecure 64-bit Passed
Testing the distro type
ubuntu is Supported!
Installing dependencies with apt-get
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.PH05OFxvL4 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/maxmind-ppa.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-java.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
gpg: requesting key 7F0CEB10 from hkp server keyserver.ubuntu.com
gpg: key 7F0CEB10: "Richard Kreuter <richard@10gen.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
'universe' distribution component is already enabled for all sources.
Ign http://downloads-distro.mongodb.org dist InRelease
Hit http://downloads-distro.mongodb.org dist Release.gpg
Hit http://downloads-distro.mongodb.org dist Release
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://downloads-distro.mongodb.org dist/10gen amd64 Packages
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en_US
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en
Hit http://download.rethinkdb.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://download.rethinkdb.com trusty Release
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://ppa.launchpad.net trusty InRelease
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
Note, selecting 'upx-ucl' instead of 'upx'
build-essential is already the newest version.
libjpeg-dev is already the newest version.
libpcap-dev is already the newest version.
libsasl2-dev is already the newest version.
libxslt1-dev is already the newest version.
python-dev is already the newest version.
swig is already the newest version.
zip is already the newest version.
zlib1g-dev is already the newest version.
libfuzzy-dev is already the newest version.
ssdeep is already the newest version.
upx-ucl is already the newest version.
curl is already the newest version.
git is already the newest version.
libevent-dev is already the newest version.
libldap2-dev is already the newest version.
libpcre3-dev is already the newest version.
libssl-dev is already the newest version.
libxml2-dev is already the newest version.
libyaml-dev is already the newest version.
numactl is already the newest version.
p7zip-full is already the newest version.
python-pip is already the newest version.
mongodb-org is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Installing Python Dependencies
Requirement already satisfied: M2Crypto in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: typing in /usr/local/lib/python2.7/dist-packages (from M2Crypto)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting git+https://github.com/brianz/django-debug-toolbar-mongo.git (from -r requirements.txt (line 11))
  Cloning https://github.com/brianz/django-debug-toolbar-mongo.git to /tmp/pip-Z3sjfM-build
Collecting git+https://github.com/frbapolkosnik/django-tastypie-mongoengine.git (from -r requirements.txt (line 16))
  Cloning https://github.com/frbapolkosnik/django-tastypie-mongoengine.git to /tmp/pip-NuyQX7-build
Collecting git+https://github.com/MongoEngine/django-mongoengine.git (from -r requirements.txt (line 21))
  Cloning https://github.com/MongoEngine/django-mongoengine.git to /tmp/pip-1kam9v-build
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: Django<1.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: amqp in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: anyjson in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: billiard in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: biplist in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: celery in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: defusedxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: django-celery in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: django-debug-toolbar in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: django-debug-toolbar-template-profiler in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: django-debug-toolbar-template-timings in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: django-debug-toolbar-vcs-info in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: django-tastypie==0.13.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: kombu in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already up-to-date: mongoengine==0.10.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already up-to-date: pip>=8.1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22))
Requirement already up-to-date: pydeep==0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Requirement already up-to-date: pymongo==3.2.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 24))
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 25))
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 26))
Requirement already up-to-date: python-ldap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 27))
Requirement already up-to-date: python-magic==0.4.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 28))
Requirement already up-to-date: python-mimeparse in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 29))
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 30))
Requirement already up-to-date: pyyaml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 31))
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 32))
Requirement already up-to-date: setuptools>=28.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 33))
Requirement already up-to-date: simplejson in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 34))
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 35))
Requirement already up-to-date: ushlex in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 36))
Requirement already up-to-date: wsgiref in /usr/lib/python2.7 (from -r requirements.txt (line 37))
Requirement already up-to-date: olefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 38))
Requirement already up-to-date: pyimpfuzzy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 39))
Requirement already up-to-date: m2crypto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 40))
Requirement already up-to-date: vine>=1.1.3 in /usr/local/lib/python2.7/dist-packages (from amqp->-r requirements.txt (line 3))
Requirement already up-to-date: sqlparse>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar->-r requirements.txt (line 10))
Requirement already up-to-date: dateutils in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar-vcs-info->-r requirements.txt (line 14))
Requirement already up-to-date: pefile in /usr/local/lib/python2.7/dist-packages (from pyimpfuzzy->-r requirements.txt (line 39))
Requirement already up-to-date: typing in /usr/local/lib/python2.7/dist-packages (from m2crypto->-r requirements.txt (line 40))
Collecting argparse (from dateutils->django-debug-toolbar-vcs-info->-r requirements.txt (line 14))
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: django-debug-toolbar-mongo, django-tastypie-mongoengine, django-mongoengine, argparse
  Found existing installation: django-debug-toolbar-mongo 0.1.10
    Uninstalling django-debug-toolbar-mongo-0.1.10:
      Successfully uninstalled django-debug-toolbar-mongo-0.1.10
  Running setup.py install for django-debug-toolbar-mongo ... done
  Found existing installation: django-tastypie-mongoengine 0.4.7
    Uninstalling django-tastypie-mongoengine-0.4.7:
      Successfully uninstalled django-tastypie-mongoengine-0.4.7
  Running setup.py install for django-tastypie-mongoengine ... done
  Found existing installation: django-mongoengine 0.2.1
    Uninstalling django-mongoengine-0.2.1:
      Successfully uninstalled django-mongoengine-0.2.1
  Running setup.py install for django-mongoengine ... done
  Found existing installation: argparse 1.2.1
    Not uninstalling argparse at /usr/lib/python2.7, as it is in the standard library.
Successfully installed argparse-1.4.0 django-debug-toolbar-mongo-0.1.10 django-mongoengine-0.2.1 django-tastypie-mongoengine-0.4.7
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Dependency installation complete!
Mongo already installed
Database configuration file exists. skipping!
Creating default collections
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/services/__init__.py", line 3, in <module>
    manager = svc_manager()
  File "/data/crits/crits/services/core.py", line 52, in __init__
    self._register_services(Service)
  File "/data/crits/crits/services/core.py", line 143, in _register_services
    new_config = service.get_config(existing_config)
  File "/data/crits/data/crits_services/chopshop_service/__init__.py", line 47, in get_config
    fields = forms.ChopShopConfigForm().fields
  File "/data/crits/data/crits_services/chopshop_service/forms.py", line 36, in __init__
    super(ChopShopConfigForm, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in __init__
    self.label_suffix = label_suffix if label_suffix is not None else _(':')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 84, in ugettext
    return _trans.ugettext(message)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 330, in ugettext
    return do_translate(message, 'ugettext')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 307, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 209, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 118, in __init__
    self._add_installed_apps_translations()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

**Comment by apolkosnik** [comment]
Can you please update services (git pull)?

**Comment by Tom-Gorup** [comment]
Is there a specific location, should I delete the contents of the services dir and `git pull` from the services github? 

```
:/data/crits/crits/services# ls
analysis_result.py   api.py        core.py   handlers.py   __init__.py   service.py   static     test     urls.pyc  views.pyc
analysis_result.pyc  connector.py  core.pyc  handlers.pyc  __init__.pyc  service.pyc  templates  urls.py  views.py
:/data/crits/crits/services# git pull
Already up-to-date.
```

**Comment by apolkosnik** [comment]
do the pull in /data/crits/data/crits_services/
typically the crits_services should live in /data, so the path should be /data/crits_services/

**Comment by Tom-Gorup** [comment]
Worked, thank you! Don't mean to piggyback on this issue, but I am having a second problem with the ALLOWED_HOSTS. I don't think I'm making the change in the correct location... I've tried changing the "ALLOWED_HOSTS" in the settings.py. 

Appreciate the assist!

from:
`ALLOWED_HOSTS =             crits_config.get('allowed_hosts', ['*'])`

To:
`ALLOWED_HOSTS =             crits_config.get('allowed_hosts', ['x.x.x.x'])`

**Comment by apolkosnik** [comment]
You can change that in the Web UI

**Comment by Tom-Gorup** [comment]
Hm... I'm getting "A server error occurred.  Please contact the administrator." in the web UI and the backend:

```
Django version 1.8.17, using settings 'crits.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 207, in get_response
    return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 384, in get_traceback_html
    return t.render(c)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 152, in build_absolute_uri
    host=self.get_host(),
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 102, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'x.x.x.x:8080'. You may need to add u'x.x.x.x' to ALLOWED_HOSTS.
[18/Jan/2017 16:48:06] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 207, in get_response
    return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 384, in get_traceback_html
    return t.render(c)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 152, in build_absolute_uri
    host=self.get_host(),
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 102, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'x.x.x.x:8080'. You may need to add u'x.x.x.x' to ALLOWED_HOSTS.
```

**Comment by apolkosnik** [comment]
https://github.com/crits/crits/wiki/Production-grade-CRITs-install#set-your-allowed-hosts

**Comment by Tom-Gorup** [comment]
You are the man! Thank you!
