### ISSUE TITLE
Install CRITs on OS X

### ISSUE THREAD

**Issue by alpha-7** [crits/crits#909]
I'm getting to following error while attempting to install CRITs on OS X: 

 ~/Documents/crits   master ●  sh script/bootstrap 4
Database configuration file exists. skipping!
Creating default collections
Exception AttributeError: "'Cursor' object has no attribute '_Cursor__id'" in <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x10924f750>> ignored
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/pro/Documents/crits/crits/services/__init__.py", line 3, in <module>
    manager = svc_manager()
  File "/Users/pro/Documents/crits/crits/services/core.py", line 52, in __init__
    self._register_services(Service)
  File "/Users/pro/Documents/crits/crits/services/core.py", line 173, in _register_services
    for svc in svcs:
  File "/Library/Python/2.7/site-packages/mongoengine/queryset/queryset.py", line 157, in _iter_results
    self._populate_cache()
  File "/Library/Python/2.7/site-packages/mongoengine/queryset/queryset.py", line 167, in _populate_cache
    self._result_cache.append(self.next())
  File "/Library/Python/2.7/site-packages/mongoengine/queryset/queryset.py", line 1148, in next
    raw_doc = self._cursor.next()
  File "/Library/Python/2.7/site-packages/mongoengine/queryset/queryset.py", line 1194, in _cursor
    **self._cursor_args)
  File "/Library/Python/2.7/site-packages/pymongo/collection.py", line 1239, in find
    return Cursor(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'snapshot'

I've tried with both MongoDB 3.4.4 and 2.6.
pymongo==3.2.2
mongoengine==0.10.6
Django==1.8.18
django-mongoengine==0.2.1
django-tastypie-mongoengine==0.4.7

Any assistance would be greatly appreciated.

**Comment by apolkosnik** [comment]
You need to uninstall pymongo and mongoengine. Please make sure that you install pymongo==2.8.1 and mongoengine==0.8.8.

**Comment by alpha-7** [comment]
Just tried that and get the same error.  The requirements.txt has pymongo==3.2.2
and mongoengine==0.10.6.

**Comment by alpha-7** [comment]
Tried creating a Docker image using the included Dockerfile but that fails as well:

_Step 12/14 : RUN sh contrib/mongo/mongod_start.sh && python manage.py users -u admin -p "pass1PASS123!" -s -i -a -A -e admin@crits.crits -f "first" -l "last" -o "no-org"
 ---> Running in ff78fa1c5c70
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
Usage: manage.py users [options]

Add and edit a CRITs user. If "-a" is not used, we will try to edit.

manage.py: error: no such option: -A_

**Comment by apolkosnik** [comment]
read UPDATING ... Roles were recently merged...
