### ISSUE TITLE
HTTP 500 error after login

### ISSUE THREAD

**Issue by ignacioj** [crits/crits#951]
I have installed CRITs using the bootstrap. When I try to enter with the user created in the process I receive an error:
..............................
[27/Nov/2017 08:32:53] "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[27/Nov/2017 08:32:53] "GET /new_images/crits_logo.png HTTP/1.1" 304 0
[27/Nov/2017 08:32:53] "GET /new_images/top_bar_bg_dev.png HTTP/1.1" 304 0
[27/Nov/2017 08:32:53] "GET /new_images/textbox_bg.jpg HTTP/1.1" 304 0
[27/Nov/2017 08:32:54] "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 304 0
[27/Nov/2017 08:33:14] "POST /login/ HTTP/1.1" 500 21952

After enabling logging this is the content of the report:

ERROR 2017-11-27 08:33:14,710 django.request Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/middleware.py", line 50, in process_response
    request.session.save()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/django/sessions.py", line 101, in save
    s.save(force_insert=must_create)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 294, in save
    raise OperationError(message % unicode(err))
OperationError: Could not save document (wrong type for 'multi' field, expected boolean, found multi: null)

Any help would be appreciated. Thank you.

**Comment by ignacioj** [comment]
After reading #933 I tried patching: queryset._collection.remove(queryset._query, **write_concern)
But It didn't work.
I tried downloading and installing the code before the commit mentioned:
"Update the requirements for faster version of mongoengine"   c85f9ac

It is working without errors.

**Comment by Hcooperi** [comment]
I encountered this error as well on a fresh Ubuntu 16.04 LTS 64-bit install. There is an error on login which if fixed, then throws mongo errors for the _insert() command when trying to add a anything in the interface (too many arguments). Reverting to c85f9ac works.

Commands to get a the base install working on fresh Ubuntu:
`git clone https://github.com/crits/crits.git
git checkout c85f9ac
sh script/bootstrap`

Afterwards, starting mongo, adding a crits admin user, logging on and adding a source all work.

**Comment by mgoffin** [comment]
Could someone post a `pip freeze` so we can see what versions of libraries you are using when the error happens? Thanks!

**Comment by Hcooperi** [comment]
Reproduced. Base Ubuntu install, pulled latest git, ran bootstrap.

Server:
```
Running Server on 0.0.0.0 Port 8080
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2017 - 13:27:28
Django version 1.8.18, using settings 'crits.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[REDACTED NORMAL GET REQUESTS]
[12/Dec/2017 13:27:50] "POST /login/ HTTP/1.1" 500 22382
```

POST:
```
username = u'[REDACTED]'
next_url = u'/'
password = u"[REDACTED]"
```


Traceback from POST response:
```
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  223.                 response = middleware_method(request, response)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/middleware.py" in process_response
  50.                         request.session.save()
File "/usr/local/lib/python2.7/dist-packages/mongoengine/django/sessions.py" in save
  101.             s.save(force_insert=must_create)
File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py" in save
  294.             raise OperationError(message % unicode(err))

Exception Type: OperationError at /login/
Exception Value: Could not save document (wrong type for 'multi' field, expected boolean, found multi: null)
Request information:
GET: No GET data
```

pip freeze:
```
adium-theme-ubuntu==0.3.4
amqp==2.2.2
anyjson==0.3.3
billiard==3.5.0.3
biplist==1.0.3
celery==4.1.0
certifi==2017.11.5
chardet==3.0.4
dateutils==0.6.6
defusedxml==0.5.0
Django==1.8.18
django-celery==3.2.2
django-debug-toolbar==1.9.1
django-debug-toolbar-mongo==0.1.10
django-debug-toolbar-template-profiler==1.0.2
django-debug-toolbar-template-timings==0.7
django-debug-toolbar-vcs-info==1.2.0
django-mongoengine==0.2.1
django-tastypie==0.13.3
django-tastypie-mongoengine==0.4.7
future==0.16.0
idna==2.6
kombu==4.1.0
lxml==4.1.1
M2Crypto==0.27.0
mongoengine==0.8.8
olefile==0.44
pefile==2017.11.5
Pillow==4.3.0
pycrypto==2.6.1
pydeep==0.2
pyimpfuzzy==0.2
pymongo==2.8.1
pyparsing==2.2.0
python-dateutil==2.6.1
python-ldap==2.5.2
python-magic==0.4.6
python-mimeparse==1.6.0
pytz==2017.3
PyYAML==3.12
qrcode==5.3
requests==2.18.4
simplejson==3.13.2
six==1.11.0
sqlparse==0.2.4
typing==3.6.2
unity-lens-photos==1.0
urllib3==1.22
ushlex==0.99
vine==1.1.4
```

**Comment by mgoffin** [comment]
Just curious, but can you try forcing Django down to 1.8.13?

**Comment by mgoffin** [comment]
That interaction looks to be a conflict of interest between the version of MongoEngine and the version of PyMongo.  Seems like MongoEngine is providing more data than PyMongo knows what to do with. Unfortunately my environment is not setup to test this right now.

If you could look at the last two Files and lines in your traceback on your host machine, it should show you the issue. The resolution to this is obviously the correct pairing of Mongoengine to PyMongo. The right pair I can't say. I thought the one we had in requirements works but evidently not.

**Comment by Hcooperi** [comment]
Yeah, upgrading mongoengine to 0.11.0+ seems to work with any version of pymongo 2.8.8+ including the latest of both.

The master seems to have an issue with adding sources once fixed (the changes to the roles I'm guessing), but a reversion to baa7a03 and using the latest versions works. As of this post that is mongoengine 0.15.0 and pymongo 3.6.0.

**Comment by brycampbell** [comment]
What was the solution to this? using a lower version?

**Comment by apolkosnik** [comment]
This issue has to do with saving to the DB session data.
Django has some lengthy 
https://docs.djangoproject.com/en/1.10/topics/http/sessions/#module-django.contrib.sessions

Instead we could try switching to a slightly different SESSION_ENGINE in settings.py:
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
