### ISSUE TITLE
Multiple values for keyword argument 'tlp'" when using API to ingest EML email 

### ISSUE THREAD

**Issue by swedishmike-net** [crits/crits#952]
When using below script, i receive this error:
[{u'error_message': u"handle_eml() got multiple values for keyword argument 'tlp'", u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 219, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 450, in dispatch_list\n    return self.dispatch(\'list\', request, **kwargs)\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py", line 428, in dispatch\n    return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py", line 391, in _wrap_request\n    return fun()\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie_mongoengine/resources.py", line 428, in <lambda>\n    return self._wrap_request(request, lambda: super(MongoEngineResource, self).dispatch(request_type, request, **kwargs))\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 482, in dispatch\n    response = method(request, **kwargs)\n\n  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 1384, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File "/data/crits/crits/emails/api.py", line 96, in obj_create\n    confidence=confidence, bucket_list=bucket_list, ticket=ticket)\n\nTypeError: handle_eml() got multiple values for keyword argument \'tlp\'\n'}]

*******************************************************************************************************
import requests
import json
url = 'https://X.X.X.X/api/v1/emails/'
files = { 'filedata': open('/temp/xxxx.eml','rb') }
data = {
'api_key':'xxxxxx',
'username':'xxxxx',
'upload_type': 'eml',
'tlp': 'amber'
}
crits = requests.post(url, data=data, files=files, verify=False)
response = json.loads(crits.text)
print [response]
*******************************************************************************************************
Looking at /data/crits/crits/emails/api.py and changing:
from:
                                user, 'EML Upload' + method, tlp=tlp, campaign=campaign,
to:
                                user, 'EML Upload' + method, tlp, campaign=campaign,

I now get the error:
[{u'message': u'Missing source information.', u'type': u'Email', u'return_code': 1}]

I've tried multiple .eml files (with and without attachments) and the errors remain even after setting sourcename/source/source_name.

**Comment by Frontman113** [comment]
I am seeing a similar issue. Any luck?

**Comment by yalbertorosso** [comment]
This issue seems to be caused by an ambiguous use of positional arguments.
On /emails/api.py's the obj_create() method calls the handle_eml() method this way:

```
result = handle_eml(filedata, source, reference,
                        **user, 'EML Upload' + method, tlp=tlp**, campaign=campaign,
                        confidence=confidence, bucket_list=bucket_list, ticket=ticket)
```

Anyways, handle_eml() is defined with this order for its own arguments:

```
def handle_eml(data, sourcename, reference, **method, tlp, user**, campaign=None,
               confidence=None, bucket_list=None, ticket=None,
               related_id=None, related_type=None, relationship_type=None)
```

**Comment by trentprynn** [comment]
Seeing the same issue, anyone know if this has / is going to be fixed?
